export { DesignSystemPage } from "./DesignSystemPage/DesignSystemPage"
export { HomePage } from "./HomePage/HomePage"
export { ProductDetailPage } from "./ProductDetailPage/ProductDetailPage"
export { SearchPage } from "./SearchPage/SearchPage"
export { CartPage } from "./CartPage/CartPage"
export { OrderPage } from "./OrderPage/OrderPage"